"""
Package pycymbal provides a simplified Go API for Python bindings

"""
# python wrapper for package github.com/dwash/py-cymbal/pycymbal within overall package pycymbal
# This is what you import to use the package.
# File is generated by gopy. Do not edit.
# gopy gen -vm=python3 ./pycymbal

# the following is required to enable dlopen to open the _go.so file
import os,sys,inspect,collections
try:
	import collections.abc as _collections_abc
except ImportError:
	_collections_abc = collections

cwd = os.getcwd()
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
os.chdir(currentdir)
from . import _pycymbal
from . import go

os.chdir(cwd)

# to use this code in your end-user python file, import it as follows:
# from pycymbal import pycymbal
# and then refer to everything using pycymbal. prefix
# packages imported by this package listed below:




# ---- Types ---

# Python type for slice []pycymbal.ImpactResult
class Slice_pycymbal_ImpactResult(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_pycymbal.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_pycymbal.IncRef(self.handle)
		else:
			self.handle = _pycymbal.Slice_pycymbal_ImpactResult_CTor()
			_pycymbal.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Iterable):
					raise TypeError('Slice_pycymbal_ImpactResult.__init__ takes a sequence as argument')
				for elt in args[0]:
					self.append(elt)
	def __del__(self):
		_pycymbal.DecRef(self.handle)
	def __str__(self):
		s = 'pycymbal.Slice_pycymbal_ImpactResult len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' ['
		if len(self) < 120:
			s += ', '.join(map(str, self)) + ']'
		return s
	def __repr__(self):
		return 'pycymbal.Slice_pycymbal_ImpactResult([' + ', '.join(map(str, self)) + '])'
	def __len__(self):
		return _pycymbal.Slice_pycymbal_ImpactResult_len(self.handle)
	def __getitem__(self, key):
		if isinstance(key, slice):
			if key.step == None or key.step == 1:
				st = key.start
				ed = key.stop
				if st == None:
					st = 0
				if ed == None:
					ed = _pycymbal.Slice_pycymbal_ImpactResult_len(self.handle)
				return Slice_pycymbal_ImpactResult(handle=_pycymbal.Slice_pycymbal_ImpactResult_subslice(self.handle, st, ed))
			return [self[ii] for ii in range(*key.indices(len(self)))]
		elif isinstance(key, int):
			if key < 0:
				key += len(self)
			if key < 0 or key >= len(self):
				raise IndexError('slice index out of range')
			return ImpactResult(handle=_pycymbal.Slice_pycymbal_ImpactResult_elem(self.handle, key))
		else:
			raise TypeError('slice index invalid type')
	def __setitem__(self, idx, value):
		if idx < 0:
			idx += len(self)
		if idx < len(self):
			_pycymbal.Slice_pycymbal_ImpactResult_set(self.handle, idx, value.handle)
			return
		raise IndexError('slice index out of range')
	def __iadd__(self, value):
		if not isinstance(value, _collections_abc.Iterable):
			raise TypeError('Slice_pycymbal_ImpactResult.__iadd__ takes a sequence as argument')
		for elt in value:
			self.append(elt)
		return self
	def __iter__(self):
		self.index = 0
		return self
	def __next__(self):
		if self.index < len(self):
			rv = ImpactResult(handle=_pycymbal.Slice_pycymbal_ImpactResult_elem(self.handle, self.index))
			self.index = self.index + 1
			return rv
		raise StopIteration
	def append(self, value):
		_pycymbal.Slice_pycymbal_ImpactResult_append(self.handle, value.handle)
	def copy(self, src):
		""" copy emulates the go copy function, copying elements into this list from source list, up to min of size of each list """
		mx = min(len(self), len(src))
		for i in range(mx):
			self[i] = src[i]

# Python type for slice []pycymbal.RefResult
class Slice_pycymbal_RefResult(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_pycymbal.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_pycymbal.IncRef(self.handle)
		else:
			self.handle = _pycymbal.Slice_pycymbal_RefResult_CTor()
			_pycymbal.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Iterable):
					raise TypeError('Slice_pycymbal_RefResult.__init__ takes a sequence as argument')
				for elt in args[0]:
					self.append(elt)
	def __del__(self):
		_pycymbal.DecRef(self.handle)
	def __str__(self):
		s = 'pycymbal.Slice_pycymbal_RefResult len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' ['
		if len(self) < 120:
			s += ', '.join(map(str, self)) + ']'
		return s
	def __repr__(self):
		return 'pycymbal.Slice_pycymbal_RefResult([' + ', '.join(map(str, self)) + '])'
	def __len__(self):
		return _pycymbal.Slice_pycymbal_RefResult_len(self.handle)
	def __getitem__(self, key):
		if isinstance(key, slice):
			if key.step == None or key.step == 1:
				st = key.start
				ed = key.stop
				if st == None:
					st = 0
				if ed == None:
					ed = _pycymbal.Slice_pycymbal_RefResult_len(self.handle)
				return Slice_pycymbal_RefResult(handle=_pycymbal.Slice_pycymbal_RefResult_subslice(self.handle, st, ed))
			return [self[ii] for ii in range(*key.indices(len(self)))]
		elif isinstance(key, int):
			if key < 0:
				key += len(self)
			if key < 0 or key >= len(self):
				raise IndexError('slice index out of range')
			return RefResult(handle=_pycymbal.Slice_pycymbal_RefResult_elem(self.handle, key))
		else:
			raise TypeError('slice index invalid type')
	def __setitem__(self, idx, value):
		if idx < 0:
			idx += len(self)
		if idx < len(self):
			_pycymbal.Slice_pycymbal_RefResult_set(self.handle, idx, value.handle)
			return
		raise IndexError('slice index out of range')
	def __iadd__(self, value):
		if not isinstance(value, _collections_abc.Iterable):
			raise TypeError('Slice_pycymbal_RefResult.__iadd__ takes a sequence as argument')
		for elt in value:
			self.append(elt)
		return self
	def __iter__(self):
		self.index = 0
		return self
	def __next__(self):
		if self.index < len(self):
			rv = RefResult(handle=_pycymbal.Slice_pycymbal_RefResult_elem(self.handle, self.index))
			self.index = self.index + 1
			return rv
		raise StopIteration
	def append(self, value):
		_pycymbal.Slice_pycymbal_RefResult_append(self.handle, value.handle)
	def copy(self, src):
		""" copy emulates the go copy function, copying elements into this list from source list, up to min of size of each list """
		mx = min(len(self), len(src))
		for i in range(mx):
			self[i] = src[i]

# Python type for slice []pycymbal.SymbolResult
class Slice_pycymbal_SymbolResult(go.GoClass):
	""""""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameter is a python list that we copy from
		"""
		self.index = 0
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_pycymbal.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_pycymbal.IncRef(self.handle)
		else:
			self.handle = _pycymbal.Slice_pycymbal_SymbolResult_CTor()
			_pycymbal.IncRef(self.handle)
			if len(args) > 0:
				if not isinstance(args[0], _collections_abc.Iterable):
					raise TypeError('Slice_pycymbal_SymbolResult.__init__ takes a sequence as argument')
				for elt in args[0]:
					self.append(elt)
	def __del__(self):
		_pycymbal.DecRef(self.handle)
	def __str__(self):
		s = 'pycymbal.Slice_pycymbal_SymbolResult len: ' + str(len(self)) + ' handle: ' + str(self.handle) + ' ['
		if len(self) < 120:
			s += ', '.join(map(str, self)) + ']'
		return s
	def __repr__(self):
		return 'pycymbal.Slice_pycymbal_SymbolResult([' + ', '.join(map(str, self)) + '])'
	def __len__(self):
		return _pycymbal.Slice_pycymbal_SymbolResult_len(self.handle)
	def __getitem__(self, key):
		if isinstance(key, slice):
			if key.step == None or key.step == 1:
				st = key.start
				ed = key.stop
				if st == None:
					st = 0
				if ed == None:
					ed = _pycymbal.Slice_pycymbal_SymbolResult_len(self.handle)
				return Slice_pycymbal_SymbolResult(handle=_pycymbal.Slice_pycymbal_SymbolResult_subslice(self.handle, st, ed))
			return [self[ii] for ii in range(*key.indices(len(self)))]
		elif isinstance(key, int):
			if key < 0:
				key += len(self)
			if key < 0 or key >= len(self):
				raise IndexError('slice index out of range')
			return SymbolResult(handle=_pycymbal.Slice_pycymbal_SymbolResult_elem(self.handle, key))
		else:
			raise TypeError('slice index invalid type')
	def __setitem__(self, idx, value):
		if idx < 0:
			idx += len(self)
		if idx < len(self):
			_pycymbal.Slice_pycymbal_SymbolResult_set(self.handle, idx, value.handle)
			return
		raise IndexError('slice index out of range')
	def __iadd__(self, value):
		if not isinstance(value, _collections_abc.Iterable):
			raise TypeError('Slice_pycymbal_SymbolResult.__iadd__ takes a sequence as argument')
		for elt in value:
			self.append(elt)
		return self
	def __iter__(self):
		self.index = 0
		return self
	def __next__(self):
		if self.index < len(self):
			rv = SymbolResult(handle=_pycymbal.Slice_pycymbal_SymbolResult_elem(self.handle, self.index))
			self.index = self.index + 1
			return rv
		raise StopIteration
	def append(self, value):
		_pycymbal.Slice_pycymbal_SymbolResult_append(self.handle, value.handle)
	def copy(self, src):
		""" copy emulates the go copy function, copying elements into this list from source list, up to min of size of each list """
		mx = min(len(self), len(src))
		for i in range(mx):
			self[i] = src[i]


#---- Enums from Go (collections of consts with same type) ---


#---- Constants from Go: Python can only ask that you please don't change these! ---


# ---- Global Variables: can only use functions to access ---


# ---- Interfaces ---


# ---- Structs ---

# Python type for struct pycymbal.RefResult
class RefResult(go.GoClass):
	"""RefResult represents a reference to a symbol\n"""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_pycymbal.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_pycymbal.IncRef(self.handle)
		else:
			self.handle = _pycymbal.pycymbal_RefResult_CTor()
			_pycymbal.IncRef(self.handle)
			if  0 < len(args):
				self.File = args[0]
			if "File" in kwargs:
				self.File = kwargs["File"]
			if  1 < len(args):
				self.Line = args[1]
			if "Line" in kwargs:
				self.Line = kwargs["Line"]
			if  2 < len(args):
				self.RelPath = args[2]
			if "RelPath" in kwargs:
				self.RelPath = kwargs["RelPath"]
			if  3 < len(args):
				self.Name = args[3]
			if "Name" in kwargs:
				self.Name = kwargs["Name"]
	def __del__(self):
		_pycymbal.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.RefResult{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.RefResult ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	@property
	def File(self):
		return _pycymbal.pycymbal_RefResult_File_Get(self.handle)
	@File.setter
	def File(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_RefResult_File_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_RefResult_File_Set(self.handle, value)
	@property
	def Line(self):
		return _pycymbal.pycymbal_RefResult_Line_Get(self.handle)
	@Line.setter
	def Line(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_RefResult_Line_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_RefResult_Line_Set(self.handle, value)
	@property
	def RelPath(self):
		return _pycymbal.pycymbal_RefResult_RelPath_Get(self.handle)
	@RelPath.setter
	def RelPath(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_RefResult_RelPath_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_RefResult_RelPath_Set(self.handle, value)
	@property
	def Name(self):
		return _pycymbal.pycymbal_RefResult_Name_Get(self.handle)
	@Name.setter
	def Name(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_RefResult_Name_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_RefResult_Name_Set(self.handle, value)

# Python type for struct pycymbal.SymbolResult
class SymbolResult(go.GoClass):
	"""SymbolResult represents a code symbol found during indexing\n"""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_pycymbal.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_pycymbal.IncRef(self.handle)
		else:
			self.handle = _pycymbal.pycymbal_SymbolResult_CTor()
			_pycymbal.IncRef(self.handle)
			if  0 < len(args):
				self.Name = args[0]
			if "Name" in kwargs:
				self.Name = kwargs["Name"]
			if  1 < len(args):
				self.Kind = args[1]
			if "Kind" in kwargs:
				self.Kind = kwargs["Kind"]
			if  2 < len(args):
				self.File = args[2]
			if "File" in kwargs:
				self.File = kwargs["File"]
			if  3 < len(args):
				self.StartLine = args[3]
			if "StartLine" in kwargs:
				self.StartLine = kwargs["StartLine"]
			if  4 < len(args):
				self.EndLine = args[4]
			if "EndLine" in kwargs:
				self.EndLine = kwargs["EndLine"]
			if  5 < len(args):
				self.Language = args[5]
			if "Language" in kwargs:
				self.Language = kwargs["Language"]
	def __del__(self):
		_pycymbal.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.SymbolResult{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.SymbolResult ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	@property
	def Name(self):
		return _pycymbal.pycymbal_SymbolResult_Name_Get(self.handle)
	@Name.setter
	def Name(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_SymbolResult_Name_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_SymbolResult_Name_Set(self.handle, value)
	@property
	def Kind(self):
		return _pycymbal.pycymbal_SymbolResult_Kind_Get(self.handle)
	@Kind.setter
	def Kind(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_SymbolResult_Kind_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_SymbolResult_Kind_Set(self.handle, value)
	@property
	def File(self):
		return _pycymbal.pycymbal_SymbolResult_File_Get(self.handle)
	@File.setter
	def File(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_SymbolResult_File_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_SymbolResult_File_Set(self.handle, value)
	@property
	def StartLine(self):
		return _pycymbal.pycymbal_SymbolResult_StartLine_Get(self.handle)
	@StartLine.setter
	def StartLine(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_SymbolResult_StartLine_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_SymbolResult_StartLine_Set(self.handle, value)
	@property
	def EndLine(self):
		return _pycymbal.pycymbal_SymbolResult_EndLine_Get(self.handle)
	@EndLine.setter
	def EndLine(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_SymbolResult_EndLine_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_SymbolResult_EndLine_Set(self.handle, value)
	@property
	def Language(self):
		return _pycymbal.pycymbal_SymbolResult_Language_Get(self.handle)
	@Language.setter
	def Language(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_SymbolResult_Language_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_SymbolResult_Language_Set(self.handle, value)

# Python type for struct pycymbal.ImpactResult
class ImpactResult(go.GoClass):
	"""ImpactResult represents a symbol impacted by changes\n"""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_pycymbal.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_pycymbal.IncRef(self.handle)
		else:
			self.handle = _pycymbal.pycymbal_ImpactResult_CTor()
			_pycymbal.IncRef(self.handle)
			if  0 < len(args):
				self.Symbol = args[0]
			if "Symbol" in kwargs:
				self.Symbol = kwargs["Symbol"]
			if  1 < len(args):
				self.Reason = args[1]
			if "Reason" in kwargs:
				self.Reason = kwargs["Reason"]
			if  2 < len(args):
				self.Severity = args[2]
			if "Severity" in kwargs:
				self.Severity = kwargs["Severity"]
	def __del__(self):
		_pycymbal.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.ImpactResult{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.ImpactResult ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	@property
	def Symbol(self):
		return SymbolResult(handle=_pycymbal.pycymbal_ImpactResult_Symbol_Get(self.handle))
	@Symbol.setter
	def Symbol(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_ImpactResult_Symbol_Set(self.handle, value.handle)
		else:
			raise TypeError("supplied argument type {t} is not a go.GoClass".format(t=type(value)))
	@property
	def Reason(self):
		return _pycymbal.pycymbal_ImpactResult_Reason_Get(self.handle)
	@Reason.setter
	def Reason(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_ImpactResult_Reason_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_ImpactResult_Reason_Set(self.handle, value)
	@property
	def Severity(self):
		return _pycymbal.pycymbal_ImpactResult_Severity_Get(self.handle)
	@Severity.setter
	def Severity(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_ImpactResult_Severity_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_ImpactResult_Severity_Set(self.handle, value)

# Python type for struct pycymbal.InvestigateResult
class InvestigateResult(go.GoClass):
	"""InvestigateResult contains detailed information about a symbol\n"""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_pycymbal.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_pycymbal.IncRef(self.handle)
		else:
			self.handle = _pycymbal.pycymbal_InvestigateResult_CTor()
			_pycymbal.IncRef(self.handle)
			if  0 < len(args):
				self.Symbol = args[0]
			if "Symbol" in kwargs:
				self.Symbol = kwargs["Symbol"]
			if  1 < len(args):
				self.Source = args[1]
			if "Source" in kwargs:
				self.Source = kwargs["Source"]
			if  2 < len(args):
				self.Kind = args[2]
			if "Kind" in kwargs:
				self.Kind = kwargs["Kind"]
			if  3 < len(args):
				self.Refs = args[3]
			if "Refs" in kwargs:
				self.Refs = kwargs["Refs"]
			if  4 < len(args):
				self.Impact = args[4]
			if "Impact" in kwargs:
				self.Impact = kwargs["Impact"]
			if  5 < len(args):
				self.Members = args[5]
			if "Members" in kwargs:
				self.Members = kwargs["Members"]
			if  6 < len(args):
				self.Outline = args[6]
			if "Outline" in kwargs:
				self.Outline = kwargs["Outline"]
	def __del__(self):
		_pycymbal.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.InvestigateResult{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.InvestigateResult ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	@property
	def Symbol(self):
		return SymbolResult(handle=_pycymbal.pycymbal_InvestigateResult_Symbol_Get(self.handle))
	@Symbol.setter
	def Symbol(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_InvestigateResult_Symbol_Set(self.handle, value.handle)
		else:
			raise TypeError("supplied argument type {t} is not a go.GoClass".format(t=type(value)))
	@property
	def Source(self):
		return _pycymbal.pycymbal_InvestigateResult_Source_Get(self.handle)
	@Source.setter
	def Source(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_InvestigateResult_Source_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_InvestigateResult_Source_Set(self.handle, value)
	@property
	def Kind(self):
		return _pycymbal.pycymbal_InvestigateResult_Kind_Get(self.handle)
	@Kind.setter
	def Kind(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_InvestigateResult_Kind_Set(self.handle, value.handle)
		else:
			_pycymbal.pycymbal_InvestigateResult_Kind_Set(self.handle, value)
	@property
	def Refs(self):
		return Slice_pycymbal_RefResult(handle=_pycymbal.pycymbal_InvestigateResult_Refs_Get(self.handle))
	@Refs.setter
	def Refs(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_InvestigateResult_Refs_Set(self.handle, value.handle)
		else:
			raise TypeError("supplied argument type {t} is not a go.GoClass".format(t=type(value)))
	@property
	def Impact(self):
		return Slice_pycymbal_ImpactResult(handle=_pycymbal.pycymbal_InvestigateResult_Impact_Get(self.handle))
	@Impact.setter
	def Impact(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_InvestigateResult_Impact_Set(self.handle, value.handle)
		else:
			raise TypeError("supplied argument type {t} is not a go.GoClass".format(t=type(value)))
	@property
	def Members(self):
		return Slice_pycymbal_SymbolResult(handle=_pycymbal.pycymbal_InvestigateResult_Members_Get(self.handle))
	@Members.setter
	def Members(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_InvestigateResult_Members_Set(self.handle, value.handle)
		else:
			raise TypeError("supplied argument type {t} is not a go.GoClass".format(t=type(value)))
	@property
	def Outline(self):
		return Slice_pycymbal_SymbolResult(handle=_pycymbal.pycymbal_InvestigateResult_Outline_Get(self.handle))
	@Outline.setter
	def Outline(self, value):
		if isinstance(value, go.GoClass):
			_pycymbal.pycymbal_InvestigateResult_Outline_Set(self.handle, value.handle)
		else:
			raise TypeError("supplied argument type {t} is not a go.GoClass".format(t=type(value)))

# Python type for struct pycymbal.PythonCymbal
class PythonCymbal(go.GoClass):
	"""PythonCymbal provides a simplified API for Python\n"""
	def __init__(self, *args, **kwargs):
		"""
		handle=A Go-side object is always initialized with an explicit handle=arg
		otherwise parameters can be unnamed in order of field names or named fields
		in which case a new Go object is constructed first
		"""
		if len(kwargs) == 1 and 'handle' in kwargs:
			self.handle = kwargs['handle']
			_pycymbal.IncRef(self.handle)
		elif len(args) == 1 and isinstance(args[0], go.GoClass):
			self.handle = args[0].handle
			_pycymbal.IncRef(self.handle)
		else:
			self.handle = _pycymbal.pycymbal_PythonCymbal_CTor()
			_pycymbal.IncRef(self.handle)
	def __del__(self):
		_pycymbal.DecRef(self.handle)
	def __str__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.PythonCymbal{'
		first = True
		for v in pr:
			if callable(v[1]):
				continue
			if first:
				first = False
			else:
				sv += ', '
			sv += v[0] + '=' + str(v[1])
		return sv + '}'
	def __repr__(self):
		pr = [(p, getattr(self, p)) for p in dir(self) if not p.startswith('__')]
		sv = 'pycymbal.PythonCymbal ( '
		for v in pr:
			if not callable(v[1]):
				sv += v[0] + '=' + str(v[1]) + ', '
		return sv + ')'
	def Index(self, repoPath):
		"""Index(str repoPath) str, str
		
		Index indexes a repository and returns statistics
		"""
		return _pycymbal.pycymbal_PythonCymbal_Index(self.handle, repoPath)
	def Search(self, query, limit):
		"""Search(str query, int limit) []object, str
		
		Search searches for symbols matching the query
		"""
		return Slice_pycymbal_SymbolResult(handle=_pycymbal.pycymbal_PythonCymbal_Search(self.handle, query, limit))
	def Investigate(self, symbolName, fileHint):
		"""Investigate(str symbolName, str fileHint) object, str
		
		Investigate investigates a specific symbol
		"""
		return InvestigateResult(handle=_pycymbal.pycymbal_PythonCymbal_Investigate(self.handle, symbolName, fileHint))
	def FindReferences(self, symbolName, limit):
		"""FindReferences(str symbolName, int limit) []object, str
		
		FindReferences finds references to a symbol
		"""
		return Slice_pycymbal_RefResult(handle=_pycymbal.pycymbal_PythonCymbal_FindReferences(self.handle, symbolName, limit))
	def GetDBPath(self):
		"""GetDBPath() str
		
		GetDBPath returns the current database path
		"""
		return _pycymbal.pycymbal_PythonCymbal_GetDBPath(self.handle)
	def SetDBPath(self, path, goRun=False):
		"""SetDBPath(str path) 
		
		SetDBPath sets the database path directly (for testing or reuse)
		"""
		_pycymbal.pycymbal_PythonCymbal_SetDBPath(self.handle, path, goRun)


# ---- Slices ---


# ---- Maps ---


# ---- Constructors ---
def NewCymbal():
	"""NewCymbal() object
	
	NewCymbal creates a new PythonCymbal instance
	"""
	return PythonCymbal(handle=_pycymbal.pycymbal_NewCymbal())


# ---- Functions ---


